config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources 'users' do 
    resources 'recipes'
  end

  get '/search' => 'pages#search'
  get '/instructions' => 'pages#instructions'
  get '/ingredients' => 'pages#ingredients'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/' => 'pages#index'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ApplicationRecord
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	has_many :ingredients
	has_many :instructions
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :recipes

  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	# helper_method :current_user 

	# before_action :require_user, only: [:index, :show]
	
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_user
		if current_user
			true
		else
			redirect_to sessions_new_path, notice: "You must be logged in to view that page."
		end
	end
end

app/controllers/pages_controller.rb
require 'unirest'

class PagesController < ApplicationController
	def index
		p params
		@recipes = Recipe.all
		# These code snippets use an open-source library.
	end

	def search
		p params[:search]
		response = Unirest.get "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/search?limitLicense=false&number=10&offset=0&query=" + params[:search], 
			headers:{
				"X-Mashape-Key" => "nMARLGZymnmshppAMcfnST0uONvdp1lfM7XjsntqbAgkLWke3n", 
				"Accept" => "application/json"
			}	
		
		@returned = response.body

		render json: response
	end

	def ingredients
		# These code snippets use an open-source library.
		response = Unirest.get "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/#{params[:recipe_id]}/information?includeNutrition=true",
		  headers:{
		    "X-Mashape-Key" => "df5zfjHNYVmsh1rLDDYkH5pS7T4Cp1nIxb0jsnSvLpl1KIi11H",
		    "Accept" => "application/json"
		  }

		render json: response
	end

	def instructions
		response = Unirest.get "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/#{params[:recipe_id]}/analyzedInstructions?stepBreakdown=true",
		  headers:{
		    "X-Mashape-Key" => "df5zfjHNYVmsh1rLDDYkH5pS7T4Cp1nIxb0jsnSvLpl1KIi11H",
		    "Accept" => "application/json"
		  }
		  

	  render json: response
	end
end


# These code snippets use an open-source library.

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index

	end

	def new

	end
	
	def show
		@recipe = Recipe.find(params[:id])
		@user = User.find(@recipe.user_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path
		else
			flash.now[:error] = "There was a problem authenticating."
			render action: 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash.now[:logout_success] = "You have successfully logged out."
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def destroy
		session[:user_id] = nil 
	  	redirect_to '/' 
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_user
		if current_user
			true
		else
			redirect_to sessions_new_path, notice: "You must be logged in to view that page."
		end
	end
end

app/views/layouts/_header.html.erb
<header>
	<div>
		<%= image_tag('hamburger-menu.png', class: 'menu-icon') %>
	</div>
	<div>
		<%= image_tag('logo.png', class: 'logo') %>
	</div>
	<div>
		<ul>
			<% if session[:user_id] %>
				<li><%= link_to 'My Profile', user_path(id: session[:user_id]) %></li>
				<li><%= link_to 'Logout', logout_path, method: 'delete' %></li>
			<% else %>
				<li><%= link_to 'Register', new_user_path %></li>
				<li><%= link_to 'Login', login_path %></li>
			<% end %>
		</ul>
	</div>
</header>

app/views/layouts/_nav.html.erb
<aside>
	<nav>
		<ul>
			<li><%= link_to 'Home', root_path %></li>
			<% if !current_user %>
				<li><%= link_to 'Register', new_user_path %></li>
				<li><%= link_to 'Login', login_path %></li>
			<% else %>
				<li><%= link_to 'Logout', logout_path, method: :delete %></li>
			<% end %>
			<li><%= link_to 'Tips + Pointers', '#' %></li>
		</ul>
	</nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeOverflow</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <% if current_user %>
  <% else %>
  <% end %>

  
  <main id="main-wrapper">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
    <% end %>
    <%= yield %>
  </main>
</body>
</html>

app/views/pages/index.html.erb
<div id="home-header">
	<h1>Homepage</h1>
	<h3>Search for Recipes through Spoonacular!</h3>
</div>

<div id="search-form">
	<form  id="recipe-form" action="/search" method="get">
		<input id='recipe-search' type="text" name="recipe-name" placeholder="enter food name">
		<input type="submit" value="Search">
	</form>
</div>

<div id="results">
	<div id="search-recipes-results"></div>
	<div id="search-recipe-ingredients"></div>
</div>

<div id="search-recipe-result"></div>

app/views/recipes/index.html.erb
<h2>Recipes</h2>
<% @recipes.each do |r| %>
	<%= link_to "#{r.title}", user_recipe_path(r, id: r.id) %>
<% end %>

app/views/recipes/new.html.erb
<h2>New Recipe Form</h2>

app/views/recipes/show.html.erb
<h2><%= @recipe.title %></h2>
<p>Submitted by: <%= @user.first_name %> <%= @user.last_name %></p>
<div class="times">
	<p>Prep time: <%= @recipe.prep_time %> min</p>
	<p>Cook time: <%= @recipe.cook_time %> min</p>
	<p>Total time: <%= @recipe.prep_time + @recipe.cook_time %> min</p>
</div>

<div class="ingredients">
	<% @recipe.ingredients.each do |ingred| %>
	<%= ingred.title %>
	<%= ingred.amount %>
	<br />
	<% end %>
</div>
<br />

<div class="instructions">
	<ul>
		<% @recipe.instructions.each do |instruc| %>
		<li><%= instruc.step %></li>
		<% end %>
	</ul>	
</div>

<h2>@recipacular</h2>

app/views/users/new.html.erb
<h2>New User Sign Up Form</h2>

<%= form_for :user, url: users_path do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %><br />

	<%= f.label :last_name %>
	<%= f.text_field :last_name %><br />

	<%= f.label :email %>
	<%= f.text_field :email %><br />

	<%= f.label :password %>
	<%= f.password_field :password %><br />

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %><br />

	<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h2>Welcome, <%= @user.first_name.capitalize %>!</h2>
<%= link_to 'Submit New Recipe', new_user_recipe_path(user_id: session[:user_id	]) %>